<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ArrowUpRight, Brain, ClipboardCheck, Copy, LoaderCircle, Pencil, Trash2, Sparkles } from 'lucide-vue-next';
import AppShell from '@/components/AppShell.vue';
import { memoryService, type Memory, type MemoryAction } from '@/services/memory-service';
import { loadProfile, profile, type NemuSession } from '@/services/auth-service';
import { useAppStore } from '@/stores/app';

const input = ref(''); const loading = ref<MemoryAction | 'save' | null>(null); const saved = ref<Memory>(); const result = ref<{ reply: string; ok: boolean; action: MemoryAction; copyText?: string }>(); const error = ref(''); const app = useAppStore(); const account = ref<Pick<NemuSession, 'email' | 'displayName' | 'avatarUrl'> | undefined>(profile()); const avatarFailed = ref(false); const avatarRetried = ref(false);
const resultExpanded = ref(false);
const profileInitial = computed(() => account.value?.displayName?.trim().charAt(0).toUpperCase() || account.value?.email?.charAt(0).toUpperCase() || '?');
const canSubmit = computed(() => input.value.trim().length > 0 && !loading.value);
const resultIsLong = computed(() => (result.value?.reply.length ?? 0) > 220);
const displayedReply = computed(() => !result.value ? '' : resultExpanded.value || !resultIsLong.value ? result.value.reply : `${result.value.reply.slice(0, 220).trimEnd()}…`);
const loadingText = computed(() => loading.value === 'save' ? 'Menyimpan memory…' : loading.value === 'ask' ? 'Mencari di memory…' : loading.value === 'update' ? 'Menyiapkan pembaruan…' : loading.value === 'delete' ? 'Menemukan memory yang akan dihapus…' : 'Memproses…');
onMounted(async () => { try { account.value = await loadProfile(); avatarFailed.value = false; avatarRetried.value = false; } catch { /* Retain cached profile when offline. */ } });
function onAvatarError(event: Event) { const image = event.target as HTMLImageElement; if (!avatarRetried.value && account.value?.avatarUrl) { avatarRetried.value = true; image.src = `${account.value.avatarUrl}${account.value.avatarUrl.includes('?') ? '&' : '?'}retry=${Date.now()}`; return; } avatarFailed.value = true; }
async function save() { if (!canSubmit.value) return; loading.value = 'save'; result.value = undefined; resultExpanded.value = false; error.value = ''; try { saved.value = await memoryService.save(input.value.trim()); app.showToast('Tersimpan di NEMU'); input.value = ''; } catch { error.value = 'NEMU gagal menyimpan memory. Coba lagi.'; } finally { loading.value = null; } }
async function run(action: MemoryAction) { if (!canSubmit.value) return; loading.value = action; saved.value = undefined; result.value = undefined; resultExpanded.value = false; error.value = ''; try { const reply = await memoryService.act(action, input.value.trim()); result.value = { reply: reply.reply.replace(/\.+\s*$/, ''), ok: reply.ok, action, copyText: reply.copyText }; } catch { error.value = 'NEMU gagal memproses. Coba lagi.'; } finally { loading.value = null; } }
async function copyResult() { if (!result.value?.copyText) return; await navigator.clipboard.writeText(result.value.copyText); app.showToast('Teks disalin'); }
const label = (action: MemoryAction | 'save') => loading.value === action ? (action === 'ask' ? 'Mencari…' : action === 'save' ? 'Menyimpan…' : 'Memproses…') : action === 'ask' ? 'Find' : action.charAt(0).toUpperCase() + action.slice(1);
</script>

<template><AppShell><div class="page"><header class="flex items-center justify-between"><RouterLink to="/" class="flex items-center gap-2"><span class="grid size-9 place-items-center rounded-xl bg-nemu-600 text-white"><Brain :size="19" /></span><span class="leading-tight md:hidden"><span class="block text-lg font-bold tracking-tight">NEMU</span><span class="block text-[10px] font-medium text-muted">nemu.nalju.com</span></span></RouterLink><RouterLink to="/settings" class="icon-button overflow-hidden border border-line bg-white dark:bg-[#151c17]" aria-label="Buka pengaturan profil"><img v-if="account?.avatarUrl && !avatarFailed" :src="account.avatarUrl" alt="Foto profil Google" class="size-7 rounded-full object-cover" referrerpolicy="no-referrer" @error="onAvatarError"/><span v-else class="grid size-7 place-items-center rounded-full bg-[#f0c8ad] text-xs font-bold text-[#714328]">{{ profileInitial }}</span></RouterLink></header>
<section class="pt-12 sm:pt-16"><p class="text-sm font-medium text-nemu-600 dark:text-[#83d8b2]">Save now. Find later.</p><h1 class="mt-3 max-w-md text-2xl font-semibold leading-tight tracking-[-.03em] sm:text-3xl">Apa yang ingin kamu ingat?</h1><div class="surface relative mt-8 rounded-[1.75rem] border border-line p-3 shadow-[0_10px_32px_rgba(24,33,29,.05)]"><textarea v-model="input" maxlength="200" rows="4" class="w-full resize-none bg-transparent px-3 pt-3 text-[16px] leading-6 outline-none placeholder:text-muted" placeholder="Simpan apapun, dan cari kapanpun dengan mudah..." aria-label="Tulis memory atau pertanyaan" /><div class="flex justify-end px-3 pb-1 text-xs text-muted">{{ input.length }}/200</div><div class="grid grid-cols-2 gap-2 border-t border-line pt-3 sm:grid-cols-4"><button class="soft-button min-h-11 rounded-xl px-2 text-sm" :disabled="!canSubmit" @click="save"><ClipboardCheck :size="16" />{{ label('save') }}</button><button class="soft-button min-h-11 rounded-xl px-2 text-sm" :disabled="!canSubmit" @click="run('update')"><Pencil :size="16" />{{ label('update') }}</button><button class="soft-button min-h-11 rounded-xl px-2 text-sm" :disabled="!canSubmit" @click="run('delete')"><Trash2 :size="16" />{{ label('delete') }}</button><button class="primary-button min-h-11 rounded-xl px-2 text-sm" :disabled="!canSubmit" @click="run('ask')"><ArrowUpRight :size="16" />{{ label('ask') }}</button></div><Transition name="fade"><div v-if="loading" class="absolute inset-0 z-10 grid place-items-center rounded-[1.75rem] bg-white/80 p-5 backdrop-blur-sm dark:bg-[#151c17]/85"><div class="flex items-center gap-3 rounded-2xl border border-line bg-white px-4 py-3 text-sm font-medium shadow-lg dark:bg-[#202721]"><LoaderCircle :size="19" class="animate-spin text-nemu-600"/><span>{{ loadingText }}</span></div></div></Transition></div></section>
<Transition name="fade"><section v-if="saved" class="mt-5 rounded-2xl border border-nemu-100 bg-nemu-50 p-5 dark:border-nemu-500/30 dark:bg-nemu-500/10"><p class="flex items-center gap-2 text-sm font-semibold text-nemu-600 dark:text-[#93dfbc]"><ClipboardCheck :size="17" />Tersimpan</p><p class="mt-3 break-words text-base font-semibold">{{ saved.title }}</p><p class="mt-1 break-words text-sm text-muted">{{ saved.content }}</p></section></Transition><p v-if="error" role="alert" class="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-300">{{ error }}</p>
<Transition name="fade"><section v-if="result" class="mt-5 rounded-[1.5rem] border border-line bg-white p-6 dark:bg-[#151c17]"><p class="flex items-center gap-2 text-sm font-medium text-nemu-600 dark:text-[#83d8b2]"><Sparkles :size="16" />{{ result.ok ? 'NEMU' : 'NEMU belum bisa' }}</p><p class="mt-4 break-words text-lg font-semibold leading-snug tracking-[-.015em] [overflow-wrap:anywhere] sm:text-xl">{{ displayedReply }}</p><button v-if="resultIsLong" class="mt-3 text-sm font-semibold text-nemu-600 dark:text-[#93dfbc]" @click="resultExpanded = !resultExpanded">{{ resultExpanded ? 'Tampilkan lebih sedikit' : 'Selengkapnya' }}</button><div v-if="result.copyText" class="mt-5 flex items-center gap-2 rounded-xl bg-nemu-50 px-4 py-3 text-sm font-medium text-nemu-700 dark:bg-nemu-500/10 dark:text-[#b7f1d3]"><span class="min-w-0 flex-1 break-all leading-5">{{ result.copyText }}</span><button class="icon-button size-9 shrink-0 border border-nemu-100 bg-white text-nemu-600 dark:border-nemu-500/30 dark:bg-[#202721] dark:text-[#a9edcb]" type="button" aria-label="Salin nilai" title="Salin nilai" @click="copyResult"><Copy :size="17"/></button></div></section></Transition>
</div></AppShell></template>
