<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ArrowUpRight, Brain, ClipboardCheck, Mic, Pencil, Trash2, Sparkles } from 'lucide-vue-next';
import AppShell from '@/components/AppShell.vue';
import { memoryService, type Memory, type MemoryAction } from '@/services/memory-service';
import { useAppStore } from '@/stores/app';

const input = ref(''); const loading = ref<MemoryAction | 'save' | null>(null); const saved = ref<Memory>(); const recent = ref<Memory[]>([]); const result = ref<{ reply: string; ok: boolean; action: MemoryAction }>(); const error = ref(''); const app = useAppStore();
const canSubmit = computed(() => input.value.trim().length > 0 && !loading.value);
async function loadRecent() { try { recent.value = (await memoryService.list()).slice(0, 3); } catch { error.value = 'NEMU gagal memuat memory. Coba refresh.'; } }
onMounted(loadRecent);

async function save() { if (!canSubmit.value) return; loading.value = 'save'; result.value = undefined; error.value = ''; try { saved.value = await memoryService.save(input.value.trim()); recent.value = [saved.value, ...recent.value.filter((item) => item.id !== saved.value!.id)].slice(0, 3); app.showToast('Tersimpan di NEMU'); input.value = ''; } catch { error.value = 'NEMU gagal menyimpan memory. Coba lagi.'; } finally { loading.value = null; } }

async function run(action: MemoryAction) { if (!canSubmit.value) return; loading.value = action; saved.value = undefined; result.value = undefined; error.value = ''; try { const reply = await memoryService.act(action, input.value.trim()); result.value = { reply: reply.reply, ok: reply.ok, action }; if (reply.action !== 'ask' && reply.memoryId) { recent.value = (await memoryService.list()).slice(0, 3); } } catch { error.value = 'NEMU gagal memproses. Coba lagi.'; } finally { loading.value = null; } }

const label = (action: MemoryAction | 'save') => loading.value === action ? (action === 'ask' ? 'Mencari…' : action === 'save' ? 'Menyimpan…' : 'Memproses…') : action === 'ask' ? 'Ask' : action.charAt(0).toUpperCase() + action.slice(1);
function suggestion(value: string) { input.value = value; }
</script>
<template><AppShell><div class="page"><header class="flex items-center justify-between"><RouterLink to="/" class="flex items-center gap-2 text-lg font-bold tracking-tight"><span class="grid size-9 place-items-center rounded-xl bg-nemu-600 text-white"><Brain :size="19" /></span><span class="md:hidden">NEMU</span></RouterLink><button class="icon-button border border-line bg-white dark:bg-[#191f1b]" aria-label="Buka profil"><span class="grid size-7 place-items-center rounded-full bg-[#f0c8ad] text-xs font-bold text-[#714328]">A</span></button></header>
<section class="pt-12 sm:pt-16"><p class="text-sm font-medium text-nemu-600 dark:text-[#83d8b2]">Save now. Find later.</p><h1 class="mt-3 max-w-md text-3xl font-semibold leading-tight tracking-[-.035em] sm:text-4xl">Apa yang ingin kamu ingat?</h1><div class="surface mt-8 rounded-[1.75rem] border border-line p-3 shadow-[0_10px_32px_rgba(24,33,29,.05)]"><textarea v-model="input" rows="4" class="w-full resize-none bg-transparent px-3 pt-3 text-[16px] leading-6 outline-none placeholder:text-muted" placeholder="Tulis catatan, versi baru catatan, atau pertanyaan..." aria-label="Tulis memory atau pertanyaan" /><div class="flex items-center justify-between gap-2 border-t border-line pt-3"><button class="icon-button size-10 text-muted" aria-label="Input suara"><Mic :size="19" /></button><div class="grid flex-1 grid-cols-4 gap-2"><button class="soft-button min-h-11 rounded-xl px-2 text-sm" :disabled="!canSubmit" @click="save"><ClipboardCheck :size="16" />{{ label('save') }}</button><button class="soft-button min-h-11 rounded-xl px-2 text-sm" :disabled="!canSubmit" @click="run('update')"><Pencil :size="16" />{{ label('update') }}</button><button class="soft-button min-h-11 rounded-xl px-2 text-sm" :disabled="!canSubmit" @click="run('delete')"><Trash2 :size="16" />{{ label('delete') }}</button><button class="primary-button min-h-11 rounded-xl px-2 text-sm" :disabled="!canSubmit" @click="run('ask')"><ArrowUpRight :size="16" />{{ label('ask') }}</button></div></div></div></section>
<Transition name="fade"><section v-if="saved" class="mt-5 rounded-2xl border border-nemu-100 bg-nemu-50 p-5 dark:border-nemu-500/30 dark:bg-nemu-500/10"><p class="flex items-center gap-2 text-sm font-semibold text-nemu-600 dark:text-[#93dfbc]"><ClipboardCheck :size="17" />Tersimpan</p><p class="mt-3 font-semibold">{{ saved.title }}</p><p class="mt-1 text-sm text-muted">{{ saved.content }}</p></section></Transition><p v-if="error" role="alert" class="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-300">{{ error }}</p>
<Transition name="fade"><section v-if="result" class="mt-5 rounded-[1.5rem] border border-line bg-white p-6 dark:bg-[#191f1b]"><p class="flex items-center gap-2 text-sm font-medium text-nemu-600 dark:text-[#83d8b2]"><Sparkles :size="16" />{{ result.ok ? 'NEMU' : 'NEMU belum bisa' }}</p><p class="mt-4 text-2xl font-semibold leading-snug tracking-[-.02em]">{{ result.reply }}</p></section></Transition>
<section v-if="!saved && !result" class="mt-10"><p class="text-sm font-semibold">Coba mulai dengan</p><div class="mt-3 flex flex-wrap gap-2"><button v-for="suggestionText in ['IP WiFi kantor adalah…', 'Ulang tahun ibu tanggal…', 'Di mana saya simpan…?']" :key="suggestionText" class="rounded-full border border-line bg-white px-3 py-2 text-sm text-muted transition hover:border-nemu-500 hover:text-nemu-600 dark:bg-[#191f1b]" @click="suggestion(suggestionText)">{{ suggestionText }}</button></div></section><section v-if="recent.length" class="mt-10"><div class="flex items-center justify-between"><p class="text-sm font-semibold">Terakhir disimpan</p><RouterLink to="/memories" class="text-sm font-semibold text-nemu-600 dark:text-[#83d8b2]">Lihat semua</RouterLink></div><div class="mt-3 divide-y divide-line"><RouterLink v-for="memory in recent" :key="memory.id" :to="`/memories/${memory.id}`" class="block py-3"><p class="font-medium">{{ memory.title }}</p><p class="mt-1 truncate text-sm text-muted">{{ memory.content }}</p></RouterLink></div></section></div></AppShell></template>
