<template>
  <AppHeader page-title="Numbers" active="numbers" @logout="logout">
    <div class="flex-1 overflow-y-auto"><div class="max-w-5xl mx-auto p-4 space-y-4">
      <section v-if="auth.user?.role === 'agent'" class="card text-sm text-amber-300">Menu ini tidak tersedia untuk Agent.</section>
      <template v-else>
        <section class="card space-y-3">
          <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="section-title">Nomor WhatsApp</h2><p class="mt-1 text-sm text-slate-500">WABA: {{ waba.name || 'Memuat...' }}. WABA ini terkunci untuk team Anda.</p></div><div class="flex gap-2"><button class="detail-button" :disabled="syncing" @click="sync">{{ syncing ? 'Sync...' : 'Sync nomor' }}</button><button class="detail-button" @click="openAdd">Add Number</button></div></div>
          <p v-if="error" class="alert alert-error">{{ error }}</p>
        </section>
        <section class="card divide-y divide-white/5">
          <p v-if="loading" class="py-8 text-center text-sm text-slate-500">Memuat nomor...</p><p v-else-if="!numbers.length" class="py-8 text-center text-sm text-slate-500">Belum ada nomor pada WABA team ini.</p>
          <div v-for="n in numbers" :key="n.id" class="py-3 flex flex-wrap items-start justify-between gap-3"><div><p class="font-medium">{{ n.label || n.phone_number }}</p><p class="font-mono text-xs text-accent mt-1">+{{ n.phone_number }}</p><p class="text-[11px] text-slate-500 mt-1">Phone Number ID: {{ n.meta_phone_number_id }}</p></div><div class="flex flex-wrap gap-1.5 text-xs"><span class="badge">{{ n.status }}</span><span v-if="n.meta_verification_status" class="badge bg-sky-500/10 text-sky-300">{{ n.meta_verification_status }}</span><span v-if="n.meta_quality_rating" class="badge" :class="qualityClass(n.meta_quality_rating)">Quality: {{ n.meta_quality_rating }}</span><button v-if="String(n.status).toLowerCase() !== 'active'" class="detail-button" @click="continueFlow(n)">{{ String(n.meta_verification_status || '').startsWith('VERIFIED') ? 'Register' : 'Request OTP' }}</button></div></div>
        </section>
        <section v-if="showAdd" class="card space-y-3"><div class="flex justify-between"><h2 class="font-semibold">Add Number</h2><button class="text-xs text-slate-400" @click="showAdd=false">Tutup</button></div><template v-if="flow.step==='add'"><p class="text-xs text-slate-500">Verified name mengikuti nama WABA: {{ waba.name }}</p><div class="flex gap-2"><input value="62" readonly class="field w-16 text-slate-400" /><input v-model="form.phone" class="field flex-1" placeholder="8xxxxxxxxxx" @input="normalize" /></div><button class="btn" :disabled="flow.loading" @click="add">{{ flow.loading ? 'Memproses...' : 'Tambah nomor' }}</button></template><template v-else><p class="text-xs text-slate-400">Phone Number ID: <span class="font-mono text-accent">{{ flow.phoneId }}</span></p><template v-if="flow.step==='request'"><select v-model="form.method" class="field"><option>SMS</option><option>VOICE</option></select><button class="btn" :disabled="flow.loading" @click="requestOtp">Request OTP</button></template><template v-else-if="flow.step==='verify'"><input v-model="form.otp" class="field" inputmode="numeric" placeholder="Kode OTP" /><button class="btn" :disabled="flow.loading || !form.otp" @click="verify">Verify OTP</button></template><template v-else-if="flow.step==='register'"><p class="text-sm text-emerald-400">OTP terverifikasi. Siap registrasi dengan PIN server.</p><button class="btn" :disabled="flow.loading" @click="register">Register Number</button></template><template v-else><p class="text-sm text-emerald-400">Registrasi dikirim ke Meta.</p><button class="btn" :disabled="syncing" @click="sync">Sync nomor sekarang</button></template></template></section>
      </template>
    </div></div>
  </AppHeader>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { useAuthStore } from '../stores/auth'; import { api } from '../api'; import AppHeader from '../components/AppHeader.vue';
const auth=useAuthStore(), router=useRouter(), numbers=ref([]), waba=reactive({id:'',name:''}), loading=ref(false), syncing=ref(false), error=ref(''), showAdd=ref(false); const form=reactive({phone:'',method:'SMS',otp:''}), flow=reactive({step:'add',phoneId:'',loading:false});
const logout=async()=>{await auth.logout();router.push({name:'login'})}; const qualityClass=q=>({GREEN:'bg-emerald-500/10 text-emerald-300',YELLOW:'bg-amber-500/10 text-amber-300',RED:'bg-rose-500/10 text-rose-300'}[String(q).toUpperCase()]||'');
async function load(){if(auth.user?.role==='agent')return;loading.value=true;error.value='';try{const r=await api('/WaDesk/Wabas/teamNumbers',{cache:'no-store'});numbers.value=r.data?.numbers||[];Object.assign(waba,r.data?.waba||{})}catch(e){error.value=e.message}finally{loading.value=false}}
async function sync(){syncing.value=true;error.value='';try{await api('/WaDesk/Wabas/syncNumbersForTeam',{method:'POST',body:{}});await load()}catch(e){error.value=e.message}finally{syncing.value=false}}
function openAdd(){Object.assign(form,{phone:'',method:'SMS',otp:''});Object.assign(flow,{step:'add',phoneId:'',loading:false});showAdd.value=true} function normalize(){let v=String(form.phone).replace(/\D/g,'');if(v.startsWith('628'))v=v.slice(2);else if(v.startsWith('08'))v=v.slice(1);form.phone=v} function continueFlow(n){flow.phoneId=n.meta_phone_number_id;flow.step=String(n.meta_verification_status||'').toUpperCase().startsWith('VERIFIED')?'register':'request';showAdd.value=true}
async function add(){flow.loading=true;try{const r=await api('/WaDesk/Wabas/addNumber',{method:'POST',body:{phone_number:form.phone}});flow.phoneId=String(r.data?.phone_number_id||'');if(!flow.phoneId)throw new Error('Meta tidak mengembalikan Phone Number ID');flow.step='request'}catch(e){error.value=e.message}finally{flow.loading=false}} async function requestOtp(){flow.loading=true;try{await api('/WaDesk/Wabas/requestOtp',{method:'POST',body:{phone_number_id:flow.phoneId,method:form.method}});flow.step='verify'}catch(e){error.value=e.message}finally{flow.loading=false}} async function verify(){flow.loading=true;try{await api('/WaDesk/Wabas/verifyOtp',{method:'POST',body:{phone_number_id:flow.phoneId,code:form.otp}});flow.step='register'}catch(e){error.value=e.message}finally{flow.loading=false}} async function register(){flow.loading=true;try{await api('/WaDesk/Wabas/registerNumber',{method:'POST',body:{phone_number_id:flow.phoneId}});flow.step='done'}catch(e){error.value=e.message}finally{flow.loading=false}} onMounted(load);
</script>
