-- CRM mdl_main: session multi-turn MINTA_JEMPUT_ANTAR (TTL 1 jam)

CREATE TABLE IF NOT EXISTS wa_kurir_session (
  phone VARCHAR(32) NOT NULL,
  id_pelanggan INT NULL DEFAULT NULL,
  id_cabang INT NULL DEFAULT NULL,
  jenis ENUM('antar', 'jemput') NULL DEFAULT NULL,
  layanan ENUM('sameday', 'instant') NOT NULL DEFAULT 'sameday',
  step VARCHAR(40) NOT NULL DEFAULT 'ask_jenis',
  id_lokasi INT NULL DEFAULT NULL,
  lokasi_nama VARCHAR(50) NULL DEFAULT NULL,
  lokasi_detail VARCHAR(255) NULL DEFAULT NULL,
  latt DECIMAL(10,7) NULL DEFAULT NULL,
  longt DECIMAL(10,7) NULL DEFAULT NULL,
  tarif INT NULL DEFAULT NULL,
  request_text TEXT NULL,
  request_tanggal DATE NULL DEFAULT NULL,
  request_jam DECIMAL(5,2) NULL DEFAULT NULL,
  request_granted TINYINT(1) NULL DEFAULT NULL,
  driver_alt_tanggal DATE NULL DEFAULT NULL,
  driver_alt_jam DECIMAL(5,2) NULL DEFAULT NULL,
  courier_company VARCHAR(50) NULL DEFAULT NULL,
  courier_type VARCHAR(50) NULL DEFAULT NULL,
  courier_name VARCHAR(100) NULL DEFAULT NULL,
  ongkir INT NULL DEFAULT NULL,
  rates_json MEDIUMTEXT NULL,
  id_request INT NULL DEFAULT NULL,
  summary TEXT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  PRIMARY KEY (phone),
  KEY idx_expires_at (expires_at),
  KEY idx_id_cabang (id_cabang),
  KEY idx_request_grant (request_jam, request_granted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
